export const specData =
[
  { "id": 1, "specs": { "ram": "8GB", "storage": "256GB", "battery": "3349 mAh", "display": "6.1-inch OLED" }},
  { "id": 2, "specs": { "ram": "8GB", "storage": "256GB", "battery": "3900 mAh", "display": "6.1-inch AMOLED" }},
  { "id": 3, "specs": { "ram": "12GB", "storage": "256GB", "battery": "5400 mAh", "display": "6.7-inch AMOLED" }},
  { "id": 4, "specs": { "ram": "8GB", "storage": "128GB", "battery": "4575 mAh", "display": "6.2-inch OLED" }},
  { "id": 5, "specs": { "ram": "12GB", "storage": "256GB", "battery": "4610 mAh", "display": "6.36-inch AMOLED" }},
  { "id": 6, "specs": { "ram": "12GB", "storage": "256GB", "battery": "5000 mAh", "display": "6.74-inch AMOLED" }},
  { "id": 7, "specs": { "ram": "12GB", "storage": "512GB", "battery": "5000 mAh", "display": "6.78-inch AMOLED" }},
  { "id": 8, "specs": { "ram": "12GB", "storage": "256GB", "battery": "5240 mAh", "display": "6.74-inch AMOLED" }},
  { "id": 9, "specs": { "ram": "8GB", "storage": "256GB", "battery": "4815 mAh", "display": "6.67-inch OLED" }},
  { "id": 10, "specs": { "ram": "12GB", "storage": "256GB", "battery": "5000 mAh", "display": "6.5-inch OLED" }},
  { "id": 11, "specs": { "ram": "8GB", "storage": "256GB", "battery": "4400 mAh", "display": "6.55-inch OLED" }},
  { "id": 12, "specs": { "ram": "6GB", "storage": "128GB", "battery": "4500 mAh", "display": "6.67-inch AMOLED" }},
  { "id": 13, "specs": { "ram": "16GB", "storage": "512GB", "battery": "6000 mAh", "display": "6.78-inch AMOLED" }},
  { "id": 14, "specs": { "ram": "8GB", "storage": "128GB", "battery": "5000 mAh", "display": "6.4-inch AMOLED" }},
  { "id": 15, "specs": { "ram": "4GB", "storage": "128GB", "battery": "2406 mAh", "display": "4.7-inch LCD" }},
  { "id": 16, "specs": { "ram": "6GB", "storage": "128GB", "battery": "5000 mAh", "display": "6.67-inch AMOLED" }},
  { "id": 17, "specs": { "ram": "8GB", "storage": "128GB", "battery": "5000 mAh", "display": "6.67-inch AMOLED" }},
  { "id": 18, "specs": { "ram": "4GB", "storage": "128GB", "battery": "5000 mAh", "display": "6.43-inch AMOLED" }},
  { "id": 19, "specs": { "ram": "8GB", "storage": "128GB", "battery": "5000 mAh", "display": "6.7-inch AMOLED" }},
  { "id": 20, "specs": { "ram": "8GB", "storage": "256GB", "battery": "5000 mAh", "display": "6.67-inch AMOLED" }},

  { "id": 21, "specs": { "battery_life": "6 hours", "noise_cancellation": "Yes", "bluetooth": "5.3" }},
  { "id": 22, "specs": { "battery_life": "6 hours", "water_resistance": "IPX4", "bluetooth": "5.0" }},
  { "id": 23, "specs": { "battery_life": "5 hours", "noise_cancellation": "Yes", "bluetooth": "5.3" }},
  { "id": 24, "specs": { "battery_life": "8 hours", "noise_cancellation": "Yes", "bluetooth": "5.2" }},
  { "id": 25, "specs": { "battery_life": "8 hours", "mic_quality": "HD", "bluetooth": "5.2" }},
  { "id": 26, "specs": { "battery_life": "8 hours", "noise_cancellation": "No", "bluetooth": "5.2" }},
  { "id": 27, "specs": { "battery_life": "7 hours", "noise_cancellation": "Yes", "bluetooth": "5.1" }},
  { "id": 28, "specs": { "battery_life": "6 hours", "noise_cancellation": "Yes", "bluetooth": "5.2" }},
  { "id": 29, "specs": { "battery_life": "7 hours", "audio": "HiFi", "bluetooth": "5.2" }},
  { "id": 30, "specs": { "battery_life": "6 hours", "noise_cancellation": "Yes", "bluetooth": "5.2" }},
  { "id": 31, "specs": { "battery_life": "7 hours", "noise_cancellation": "Yes", "bluetooth": "5.3" }},
  { "id": 32, "specs": { "battery_life": "6 hours", "noise_cancellation": "Yes", "bluetooth": "5.2" }},
  { "id": 33, "specs": { "battery_life": "6.5 hours", "noise_cancellation": "Yes", "bluetooth": "5.2" }},
  { "id": 34, "specs": { "battery_life": "7 hours", "charging": "Warp Charge", "bluetooth": "5.2" }},
  { "id": 35, "specs": { "battery_life": "7 hours", "assistant": "Google Assistant", "bluetooth": "5.0" }},
  { "id": 36, "specs": { "battery_life": "6 hours", "noise_cancellation": "Yes", "bluetooth": "5.0" }},
  { "id": 37, "specs": { "battery_life": "8 hours", "noise_cancellation": "Yes", "bluetooth": "5.2" }},
  { "id": 38, "specs": { "battery_life": "6.5 hours", "design": "Transparent", "bluetooth": "5.2" }},
  { "id": 39, "specs": { "battery_life": "6 hours", "water_resistance": "IP55", "bluetooth": "5.0" }},
  { "id": 40, "specs": { "battery_life": "6 hours", "noise_cancellation": "Yes", "bluetooth": "5.2" }},

  { "id": 41, "specs": { "ram": "16GB", "ssd": "1TB", "screen": "16-inch", "processor": "M3 Pro" }},
  { "id": 42, "specs": { "ram": "16GB", "ssd": "512GB", "screen": "13-inch", "processor": "Intel i7" }},
  { "id": 43, "specs": { "ram": "16GB", "ssd": "1TB", "screen": "13.5-inch", "processor": "Intel i7" }},
  { "id": 44, "specs": { "ram": "16GB", "ssd": "512GB", "screen": "14-inch", "processor": "Intel i7" }},
  { "id": 45, "specs": { "ram": "16GB", "ssd": "512GB", "screen": "14-inch", "processor": "Intel i5" }},
  { "id": 46, "specs": { "ram": "16GB", "ssd": "512GB", "screen": "15-inch", "processor": "Intel i7" }},
  { "id": 47, "specs": { "ram": "8GB", "ssd": "512GB", "screen": "14-inch", "processor": "Intel i5" }},
  { "id": 48, "specs": { "ram": "16GB", "ssd": "1TB", "screen": "15.6-inch", "processor": "Intel i7" }},
  { "id": 49, "specs": { "ram": "16GB", "ssd": "1TB", "screen": "17-inch", "processor": "Intel i7" }},
  { "id": 50, "specs": { "ram": "16GB", "ssd": "512GB", "screen": "15-inch", "processor": "Intel i7" }},
  { "id": 51, "specs": { "ram": "8GB", "ssd": "512GB", "screen": "16-inch", "processor": "Intel i5" }},
  { "id": 52, "specs": { "ram": "8GB", "ssd": "512GB", "screen": "15-inch", "processor": "Intel i5" }},
  { "id": 53, "specs": { "ram": "8GB", "ssd": "512GB", "screen": "14-inch", "processor": "Intel i5" }},
  { "id": 54, "specs": { "ram": "16GB", "ssd": "1TB", "screen": "15.6-inch", "processor": "Ryzen 7" }},
  { "id": 55, "specs": { "ram": "8GB", "ssd": "256GB", "screen": "13.6-inch", "processor": "M2" }},
  { "id": 56, "specs": { "ram": "16GB", "ssd": "512GB", "screen": "13-inch", "processor": "Intel i7" }},
  { "id": 57, "specs": { "ram": "16GB", "ssd": "512GB", "screen": "15.6-inch", "processor": "Ryzen 5" }},
  { "id": 58, "specs": { "ram": "16GB", "ssd": "1TB", "screen": "16-inch", "processor": "Intel i7" }},
  { "id": 59, "specs": { "ram": "32GB", "ssd": "1TB", "screen": "15-inch", "processor": "Intel i9" }},
  { "id": 60, "specs": { "ram": "32GB", "ssd": "1TB", "screen": "16-inch", "processor": "Ryzen 9" }},

  { "id": 61, "specs": { "display": "1.9-inch", "battery_life": "18 hours", "gps": "Yes", "water_resistance": "50m" }},
  { "id": 62, "specs": { "display": "1.4-inch", "battery_life": "40 hours", "gps": "Yes", "water_resistance": "IP68" }},
  { "id": 63, "specs": { "display": "1.3-inch", "battery_life": "14 days", "gps": "Multi-band", "water_resistance": "100m" }},
  { "id": 64, "specs": { "display": "1.58-inch", "battery_life": "6 days", "gps": "Yes", "water_resistance": "50m" }},
  { "id": 65, "specs": { "display": "1.43-inch", "battery_life": "14 days", "gps": "Yes", "water_resistance": "5ATM" }},
  { "id": 66, "specs": { "display": "1.28-inch", "battery_life": "1.5 days", "gps": "Yes", "water_resistance": "3ATM" }},
  { "id": 67, "specs": { "display": "1.3-inch", "battery_life": "30 days", "gps": "Yes", "water_resistance": "50m" }},
  { "id": 68, "specs": { "display": "1.2-inch", "battery_life": "7 days", "gps": "Yes", "water_resistance": "100m" }},
  { "id": 69, "specs": { "display": "1.4-inch", "battery_life": "3 days", "gps": "Yes", "water_resistance": "IP68" }},
  { "id": 70, "specs": { "display": "1.1-inch", "battery_life": "10 days", "gps": "No", "water_resistance": "5ATM" }},
  { "id": 71, "specs": { "display": "1.78-inch", "battery_life": "18 hours", "gps": "Yes", "water_resistance": "50m" }},
  { "id": 72, "specs": { "display": "1.3-inch", "battery_life": "11 days", "gps": "Yes", "water_resistance": "5ATM" }},
  { "id": 73, "specs": { "display": "1.1-inch", "battery_life": "2 weeks", "gps": "No", "water_resistance": "30m" }},
  { "id": 74, "specs": { "display": "1.43-inch", "battery_life": "14 days", "gps": "Yes", "water_resistance": "5ATM" }},
  { "id": 75, "specs": { "display": "1.43-inch", "battery_life": "9 days", "gps": "Yes", "water_resistance": "5ATM" }},
  { "id": 76, "specs": { "display": "1.4-inch", "battery_life": "40 hours", "gps": "Yes", "water_resistance": "IP68" }},
  { "id": 77, "specs": { "display": "1.2-inch", "battery_life": "15 days", "gps": "Yes", "water_resistance": "100m" }},
  { "id": 78, "specs": { "display": "1.04-inch", "battery_life": "7 days", "gps": "Yes", "water_resistance": "50m" }},
  { "id": 79, "specs": { "display": "1.39-inch", "battery_life": "16 days", "gps": "Yes", "water_resistance": "5ATM" }},
  { "id": 80, "specs": { "display": "1.3-inch", "battery_life": "2 days", "gps": "Yes", "water_resistance": "IP68" }},

  { "id": 81, "specs": { "power": "30W", "battery_life": "12 hours", "water_resistance": "IP67" }},
  { "id": 82, "specs": { "power": "30W", "battery_life": "24 hours", "water_resistance": "IP67" }},
  { "id": 83, "specs": { "power": "30W", "battery_life": "12 hours", "water_resistance": "IP55" }},
  { "id": 84, "specs": { "power": "25W", "battery_life": "12 hours", "water_resistance": "IPX7" }},
  { "id": 85, "specs": { "power": "20W", "battery_life": "20 hours", "water_resistance": "IPX7" }},
  { "id": 86, "specs": { "power": "20W", "battery_life": "15 hours", "water_resistance": "IP67" }},
  { "id": 87, "specs": { "power": "60W", "battery_life": "18 hours", "water_resistance": "IP67" }},
  { "id": 88, "specs": { "power": "25W", "battery_life": "10 hours", "water_resistance": "IP67" }},
  { "id": 89, "specs": { "power": "30W", "battery_life": "12 hours", "water_resistance": "IPX4" }},
  { "id": 90, "specs": { "power": "40W", "battery_life": "20 hours", "water_resistance": "IP67" }},
  { "id": 91, "specs": { "power": "20W", "battery_life": "12 hours", "water_resistance": "IP67" }},
  { "id": 92, "specs": { "power": "16W", "battery_life": "24 hours", "water_resistance": "IPX7" }},
  { "id": 93, "specs": { "power": "14W", "battery_life": "24 hours", "water_resistance": "IPX7" }},
  { "id": 94, "specs": { "power": "25W", "battery_life": "20 hours", "water_resistance": "IPX4" }},
  { "id": 95, "specs": { "power": "15W", "battery_life": "13 hours", "water_resistance": "IP67" }},
  { "id": 96, "specs": { "power": "20W", "battery_life": "12 hours", "water_resistance": "IPX4" }},
  { "id": 97, "specs": { "power": "40W", "battery_life": "10 hours", "water_resistance": "IP56" }},
  { "id": 98, "specs": { "power": "20W", "battery_life": "12 hours", "water_resistance": "IP67" }},
  { "id": 99, "specs": { "power": "10W", "battery_life": "16 hours", "water_resistance": "IP67" }},
  { "id": 100, "specs": { "power": "12W", "battery_life": "24 hours", "water_resistance": "IPX7" }},

  { "id": 101, "specs": { "sensor": "45MP Full-Frame CMOS", "video": "8K 30fps", "stabilization": "In-body IS", "lens_mount": "RF Mount" } },
  { "id": 102, "specs": { "sensor": "24.5MP Full-Frame", "video": "4K 60fps", "stabilization": "Dual EXPEED 6", "lens_mount": "Z Mount" } },
  { "id": 103, "specs": { "sensor": "33MP Full-Frame", "video": "4K 60fps", "stabilization": "5-axis IBIS", "lens_mount": "E Mount" } },
  { "id": 104, "specs": { "sensor": "26MP APS-C", "video": "4K 60fps", "stabilization": "5-axis IBIS", "lens_mount": "X Mount" } },
  { "id": 105, "specs": { "sensor": "25MP Micro 4/3", "video": "5.7K 60fps", "stabilization": "Dual IS 2", "lens_mount": "MFT" } },
  { "id": 106, "specs": { "sensor": "32.5MP APS-C", "video": "4K 30fps", "stabilization": "Digital IS", "lens_mount": "EF/EF-S" } },
  { "id": 107, "specs": { "sensor": "24MP Full-Frame", "video": "4K 30fps", "stabilization": "Electronic", "lens_mount": "F Mount" } },
  { "id": 108, "specs": { "sensor": "20MP 1-inch", "video": "4K 30fps", "stabilization": "Optical + Electronic", "zoom": "24–200mm" } },
  { "id": 109, "specs": { "sensor": "23MP", "video": "5.3K 60fps", "waterproof": "10m", "stabilization": "HyperSmooth 5.0" } },
  { "id": 110, "specs": { "sensor": "64MP", "video": "4K 60fps", "stabilization": "3-axis gimbal", "zoom": "4x" } },
  { "id": 111, "specs": { "sensor": "24MP APS-C", "video": "4K 30fps", "lens_mount": "EF-M", "stabilization": "Digital IS" } },
  { "id": 112, "specs": { "sensor": "20.9MP APS-C", "video": "4K 30fps", "lens_mount": "Z Mount", "stabilization": "Electronic" } },
  { "id": 113, "specs": { "sensor": "24MP APS-C", "video": "4K 30fps", "stabilization": "Active Mode", "screen": "Fully articulating" } },
  { "id": 114, "specs": { "sensor": "26MP APS-C", "video": "4K 30fps", "lens": "23mm f/2 fixed", "stabilization": "Digital" } },
  { "id": 115, "specs": { "sensor": "24MP Full-Frame", "video": "4K 60fps", "stabilization": "Dual IS", "lens_mount": "L Mount" } },
  { "id": 116, "specs": { "sensor": "20MP Micro 4/3", "video": "4K 30fps", "stabilization": "Sensor-shift IS", "lens_mount": "MFT" } },
  { "id": 117, "specs": { "sensor": "47MP Full-Frame", "video": "4K 30fps", "lens": "28mm f/1.7 fixed", "stabilization": "Digital" } },
  { "id": 118, "specs": { "sensor": "24MP APS-C", "video": "1080p 60fps", "lens": "18.3mm f/2.8 fixed", "stabilization": "Digital" } },
  { "id": 119, "specs": { "sensor": "24MP APS-C", "video": "4K 30fps", "lens_mount": "EF/EF-S", "stabilization": "Digital IS" } },
  { "id": 120, "specs": { "sensor": "24MP APS-C", "video": "4K 30fps", "lens_mount": "E Mount", "autofocus": "Real-time tracking" } },

  { "id": 121, "specs": { "dpi": "4000 DPI", "connection": "Wireless", "buttons": 7, "battery_life": "70 days" } },
  { "id": 122, "specs": { "dpi": "26000 DPI", "connection": "Wired", "buttons": 6, "weight": "59g" } },
  { "id": 123, "specs": { "dpi": "25600 DPI", "connection": "Wired", "buttons": 11, "weight": "121g" } },
  { "id": 124, "specs": { "dpi": "12000 DPI", "connection": "Wired", "buttons": 7, "weight": "96g" } },
  { "id": 125, "specs": { "dpi": "18000 DPI", "connection": "Wired", "buttons": 8, "weight": "97g" } },
  { "id": 126, "specs": { "dpi": "25000 DPI", "connection": "Wireless", "buttons": 5, "weight": "63g" } },
  { "id": 127, "specs": { "dpi": "26000 DPI", "connection": "Wired", "buttons": 11, "weight": "101g" } },
  { "id": 128, "specs": { "dpi": "16000 DPI", "connection": "Wired", "buttons": 6, "weight": "59g" } },
  { "id": 129, "specs": { "dpi": "1000 DPI", "connection": "Bluetooth", "buttons": 3, "weight": "90g" } },
  { "id": 130, "specs": { "dpi": "1300 DPI", "connection": "Wireless", "buttons": 2, "gesture_support": true } },
  { "id": 131, "specs": { "dpi": "1000 DPI", "connection": "Bluetooth + USB", "buttons": 8, "battery_life": "24 months" } },
  { "id": 132, "specs": { "dpi": "16000 DPI", "connection": "Wired", "buttons": 16, "weight": "85g" } },
  { "id": 133, "specs": { "dpi": "18000 DPI", "connection": "Wireless", "buttons": 9, "weight": "133g" } },
  { "id": 134, "specs": { "dpi": "18000 DPI", "connection": "Wired", "buttons": 8, "sensor": "TrueMove Pro" } },
  { "id": 135, "specs": { "dpi": "16000 DPI", "connection": "Wireless", "buttons": 15, "battery_life": "240 hours" } },
  { "id": 136, "specs": { "dpi": "8500 DPI", "connection": "Wired", "buttons": 6, "weight": "61g" } },
  { "id": 137, "specs": { "dpi": "16000 DPI", "connection": "Wired", "buttons": 6, "weight": "95g" } },
  { "id": 138, "specs": { "dpi": "1000 DPI", "connection": "Bluetooth", "buttons": 3, "battery_life": "12 months" } },
  { "id": 139, "specs": { "dpi": "1000 DPI", "connection": "Bluetooth", "buttons": 3, "silent_click": true } },
  { "id": 140, "specs": { "dpi": "7200 DPI", "connection": "Wireless", "buttons": 6, "battery_life": "300 hours" } },

  { "id": 141, "specs": { "type": "Wireless ANC", "drivers": "30mm", "battery_life": "30 hours", "microphones": 8 } },
  { "id": 142, "specs": { "type": "Wireless ANC", "drivers": "40mm", "battery_life": "24 hours", "comfort": "Protein leather" } },
  { "id": 143, "specs": { "type": "Open-back wired", "impedance": "150Ω", "frequency_response": "10–41kHz", "drivers": "38mm" } },
  { "id": 144, "specs": { "type": "Studio wired", "drivers": "45mm", "impedance": "38Ω", "foldable": true } },
  { "id": 145, "specs": { "type": "Wireless", "battery_life": "22 hours", "drivers": "40mm", "noise_cancellation": true } },
  { "id": 146, "specs": { "type": "Wireless ANC", "battery_life": "30 hours", "drivers": "40mm", "voice_assistant": true } },
  { "id": 147, "specs": { "type": "Wired monitoring", "frequency_response": "5–40kHz", "drivers": "50mm", "foldable": true } },
  { "id": 148, "specs": { "type": "Wireless ANC", "battery_life": "20 hours", "microphones": 8, "drivers": "40mm" } },
  { "id": 149, "specs": { "type": "High-end wired", "drivers": "70mm", "impedance": "56Ω", "cable": "Balanced" } },
  { "id": 150, "specs": { "type": "Studio wired", "drivers": "40mm", "impedance": "44Ω", "replaceable_cable": true } },
  { "id": 151, "specs": { "type": "Wireless", "battery_life": "24 hours", "drivers": "40mm", "ANC": true } },
  { "id": 152, "specs": { "type": "Luxury ANC", "battery_life": "38 hours", "drivers": "40mm titanium", "materials": "Aluminum + Leather" } },
  { "id": 153, "specs": { "type": "Open-back wired", "drivers": "50mm", "impedance": "30Ω", "frequency_response": "5–40kHz" } },
  { "id": 154, "specs": { "type": "Wireless", "battery_life": "40 hours", "bass_boost": true, "drivers": "40mm" } },
  { "id": 155, "specs": { "type": "Wireless gaming", "battery_life": "29 hours", "drivers": "40mm", "rgb": true } },
  { "id": 156, "specs": { "type": "Gaming wired", "drivers": "50mm", "surround_sound": true, "mic": "Detachable" } },
  { "id": 157, "specs": { "type": "Gaming wired", "drivers": "53mm", "surround": true, "mic": "Noise-cancelling" } },
  { "id": 158, "specs": { "type": "Wireless ANC", "battery_life": "30 hours", "drivers": "40mm", "extra_bass": true } },
  { "id": 159, "specs": { "type": "Wireless", "battery_life": "15 hours", "drivers": "40mm", "lightweight": true } },
  { "id": 160, "specs": { "type": "Gaming wireless", "battery_life": "20 hours", "surround": true, "drivers": "50mm" } },
  
  { "id": 161, "specs": { "type": "Mechanical", "connection": "Wireless", "switches": "GL Tactile", "rgb": true } },
  { "id": 162, "specs": { "type": "Mechanical", "switches": "Razer Green", "connection": "Wired", "rgb": true } },
  { "id": 163, "specs": { "type": "Mechanical", "switches": "Cherry MX Speed", "connection": "Wired", "rgb": true } },
  { "id": 164, "specs": { "type": "Mechanical", "switches": "OmniPoint", "connection": "Wired", "adjustable_actuation": true } },
  { "id": 165, "specs": { "type": "Mechanical", "switches": "HyperX Red", "connection": "Wired", "rgb": true } },
  { "id": 166, "specs": { "type": "Mechanical", "switches": "Hot-swappable", "connection": "Wired", "rgb": true } },
  { "id": 167, "specs": { "type": "Mechanical", "switches": "Opto-Mechanical", "connection": "Wired", "wrist_rest": true } },
  { "id": 168, "specs": { "type": "Mechanical", "switches": "Cherry MX Red", "connection": "Wired", "rgb": true } },
  { "id": 169, "specs": { "type": "Mechanical", "switches": "Gateron Red", "connection": "Wired", "rgb": true } },
  { "id": 170, "specs": { "type": "Mechanical", "switches": "Cherry MX Blue", "connection": "Wired", "size": "60%" } },
  { "id": 171, "specs": { "type": "Mechanical", "switches": "Brown", "connection": "Wired", "rgb": true } },
  { "id": 172, "specs": { "type": "Mechanical", "switches": "Romer-G", "connection": "Wired", "layout": "Full-size" } },
  { "id": 173, "specs": { "type": "Membrane", "connection": "Wired", "rgb": true, "spill_resistant": true } },
  { "id": 174, "specs": { "type": "Mechanical", "switches": "Cherry MX Red", "connection": "Wired", "rgb": true } },
  { "id": 175, "specs": { "type": "Mechanical", "switches": "Cherry MX Red", "connection": "Wired", "size": "TKL" } },
  { "id": 176, "specs": { "type": "Membrane", "connection": "Wired", "rgb": true, "durability": "Splash resistant" } },
  { "id": 177, "specs": { "type": "Membrane", "connection": "Wired", "rgb": true, "silent_keys": true } },
  { "id": 178, "specs": { "type": "Membrane", "connection": "Wired", "rgb": true, "design": "Durable frame" } },
  { "id": 179, "specs": { "type": "Mechanical", "switches": "Optical Clicky", "connection": "Wired", "size": "60%" } },
  { "id": 180, "specs": { "type": "Mechanical", "switches": "Cherry MX Brown", "connection": "Wired", "design": "High-quality PBT" } },
  
  { "id": 181, "specs": { "size": "27-inch", "resolution": "4K UHD", "panel": "IPS", "refresh_rate": "60Hz" } },
  { "id": 182, "specs": { "size": "27-inch", "resolution": "QHD", "panel": "IPS", "refresh_rate": "165Hz" } },
  { "id": 183, "specs": { "size": "32-inch", "resolution": "QHD", "panel": "VA Curved", "refresh_rate": "240Hz" } },
  { "id": 184, "specs": { "size": "32-inch", "resolution": "4K HDR", "panel": "Mini-LED", "refresh_rate": "60Hz" } },
  { "id": 185, "specs": { "size": "35-inch", "resolution": "UW-QHD", "panel": "VA Curved", "refresh_rate": "100Hz" } },
  { "id": 186, "specs": { "size": "34-inch", "resolution": "UW-QHD", "panel": "IPS Curved", "refresh_rate": "144Hz" } },
  { "id": 187, "specs": { "size": "27-inch", "resolution": "QHD", "panel": "IPS", "refresh_rate": "165Hz" } },
  { "id": 188, "specs": { "size": "28-inch", "resolution": "4K UHD", "panel": "IPS", "refresh_rate": "144Hz" } },
  { "id": 189, "specs": { "size": "27-inch", "resolution": "QHD", "panel": "IPS", "refresh_rate": "165Hz" } },
  { "id": 190, "specs": { "size": "34-inch", "resolution": "UW-QHD", "panel": "IPS", "refresh_rate": "100Hz" } },
  { "id": 191, "specs": { "size": "27-inch", "resolution": "QHD", "panel": "IPS", "refresh_rate": "144Hz" } },
  { "id": 192, "specs": { "size": "27-inch", "resolution": "QHD", "panel": "IPS", "refresh_rate": "165Hz" } },
  { "id": 193, "specs": { "size": "34-inch", "resolution": "UW-QHD", "panel": "QD-OLED", "refresh_rate": "175Hz" } },
  { "id": 194, "specs": { "size": "32-inch", "resolution": "4K UHD", "panel": "VA", "features": "Smart TV OS" } },
  { "id": 195, "specs": { "size": "24-inch", "resolution": "1080p", "panel": "IPS", "refresh_rate": "144Hz" } },
  { "id": 196, "specs": { "size": "34-inch", "resolution": "UW-QHD", "panel": "IPS", "refresh_rate": "60Hz" } },
  { "id": 197, "specs": { "size": "32-inch", "resolution": "4K UHD", "panel": "IPS", "color_accuracy": "Rec.709 certified" } },
  { "id": 198, "specs": { "size": "27-inch", "resolution": "QHD", "panel": "IPS", "refresh_rate": "165Hz" } },
  { "id": 199, "specs": { "size": "25-inch", "resolution": "1080p", "panel": "IPS", "refresh_rate": "360Hz" } },
  { "id": 200, "specs": { "size": "49-inch", "resolution": "5120*1440", "panel": "VA", "refresh_rate": "120Hz" } },
  
  { "id": 201, "specs": { "screen": "12.9-inch Liquid Retina XDR", "chip": "M2", "storage": "128GB", "camera": "12MP", "os": "iPadOS" } },
  { "id": 202, "specs": { "screen": "10.9-inch Liquid Retina", "chip": "M1", "storage": "64GB", "camera": "12MP", "os": "iPadOS" } },
  { "id": 203, "specs": { "screen": "8.3-inch Liquid Retina", "chip": "A15 Bionic", "storage": "64GB", "camera": "12MP", "os": "iPadOS" } },
  { "id": 204, "specs": { "screen": "14.6-inch AMOLED", "chip": "Snapdragon 8 Gen 2", "storage": "256GB", "camera": "13MP", "os": "Android" } },
  { "id": 205, "specs": { "screen": "12.4-inch AMOLED", "chip": "Snapdragon 8 Gen 2", "storage": "128GB", "camera": "13MP", "os": "Android" } },
  { "id": 206, "specs": { "screen": "11-inch AMOLED", "chip": "Snapdragon 8 Gen 2", "storage": "128GB", "camera": "13MP", "os": "Android" } },
  { "id": 207, "specs": { "screen": "12.6-inch AMOLED", "chip": "Snapdragon 870", "storage": "256GB", "camera": "13MP", "os": "Android" } },
  { "id": 208, "specs": { "screen": "11-inch LCD", "chip": "Snapdragon 870", "storage": "128GB", "camera": "8MP", "os": "Android" } },
  { "id": 209, "specs": { "screen": "12.6-inch OLED", "chip": "Kirin 9000", "storage": "256GB", "camera": "13MP", "os": "HarmonyOS" } },
  { "id": 210, "specs": { "screen": "13-inch PixelSense", "chip": "Intel Core i5/i7", "storage": "256GB SSD", "os": "Windows 11" } },
  { "id": 211, "specs": { "screen": "10.5-inch PixelSense", "chip": "Intel Pentium/Atom", "storage": "128GB", "os": "Windows 11" } },
  { "id": 212, "specs": { "screen": "10.1-inch Full HD", "chip": "MediaTek Octa-core", "storage": "32GB", "os": "Fire OS" } },
  { "id": 213, "specs": { "screen": "8-inch HD", "chip": "MediaTek quad-core", "storage": "32GB", "os": "Fire OS" } },
  { "id": 214, "specs": { "screen": "10.4-inch LCD", "chip": "Unisoc Tiger T618", "storage": "64GB", "os": "Android" } },
  { "id": 215, "specs": { "screen": "11-inch LCD", "chip": "Snapdragon 680", "storage": "128GB", "os": "Android" } },
  { "id": 216, "specs": { "screen": "10.36-inch LCD", "chip": "Snapdragon 680", "storage": "128GB", "os": "Android" } },
  { "id": 217, "specs": { "screen": "10.1-inch LCD", "chip": "Unisoc Tiger T618", "storage": "64GB", "os": "Android" } },
  { "id": 218, "specs": { "screen": "10.4-inch LCD", "chip": "Unisoc T610", "storage": "32GB", "os": "Android" } },
  { "id": 219, "specs": { "screen": "10.1-inch LCD", "chip": "UNISOC T618", "storage": "64GB", "os": "Android" } },
  { "id": 220, "specs": { "screen": "10.4-inch LCD", "chip": "Unisoc Tiger T618", "storage": "128GB", "os": "Android" } },

  { "id": 221, "specs": { "type": "USB-C", "power": "20W", "compatibility": "iPhone/iPad" } },
  { "id": 222, "specs": { "type": "MagSafe wireless", "power": "15W", "compatibility": "iPhone" } },
  { "id": 223, "specs": { "type": "USB-C", "power": "45W", "compatibility": "Samsung devices" } },
  { "id": 224, "specs": { "type": "Wireless Duo", "power": "15W each", "compatibility": "Qi devices" } },
  { "id": 225, "specs": { "type": "SUPERVOOC", "power": "80W", "compatibility": "OnePlus devices" } },
  { "id": 226, "specs": { "type": "Warp Charge", "power": "65W", "compatibility": "OnePlus devices" } },
  { "id": 227, "specs": { "type": "USB-C GaN", "power": "65W", "ports": "dual" } },
  { "id": 228, "specs": { "type": "USB-C GaN", "power": "120W", "ports": "triple" } },
  { "id": 229, "specs": { "type": "HyperCharge", "power": "120W", "compatibility": "Xiaomi devices" } },
  { "id": 230, "specs": { "type": "SuperVOOC", "power": "80W", "compatibility": "Oppo devices" } },
  { "id": 231, "specs": { "type": "Dart Charger", "power": "65W", "compatibility": "Realme devices" } },
  { "id": 232, "specs": { "type": "USB-C", "power": "30W", "compatibility": "Google devices" } },
  { "id": 233, "specs": { "type": "SuperCharge", "power": "66W", "compatibility": "Huawei devices" } },
  { "id": 234, "specs": { "type": "USB-C", "power": "30W", "compatibility": "Sony devices" } },
  { "id": 235, "specs": { "type": "MagSafe 3-in-1", "power": "15W per device", "compatibility": "Apple devices" } },
  { "id": 236, "specs": { "type": "Dual USB-C", "power": "40W", "compatibility": "all devices" } },
  { "id": 237, "specs": { "type": "GaN", "power": "100W", "ports": "multi-device" } },
  { "id": 238, "specs": { "type": "GaN", "power": "65W", "ports": "single/compact" } },
  { "id": 239, "specs": { "type": "USB-C", "power": "33W", "compatibility": "Xiaomi devices" } },
  { "id": 240, "specs": { "type": "USB", "power": "20W", "compatibility": "Boat devices" } }
]
